import { StateOption, States } from './country-utils'

/**
 * European subdivisions based on ISO 3166-2 standard
 * Source: ISO 3166-2 and official government sources
 * Last updated: 2024-12-19
 */
export const EUROPEAN_SUBDIVISIONS: States = {
  AT: [
    { value: '1', label: 'Burgenland' },
    { value: '2', label: 'Carinthia' },
    { value: '3', label: 'Lower Austria' },
    { value: '4', label: 'Upper Austria' },
    { value: '5', label: 'Salzburg' },
    { value: '6', label: 'Styria' },
    { value: '7', label: 'Tyrol' },
    { value: '8', label: 'Vorarlberg' },
    { value: '9', label: 'Vienna' },
  ],
  BE: [
    { value: 'VAN', label: 'Antwerp' },
    { value: 'WBR', label: 'Walloon Brabant' },
    { value: 'BRU', label: 'Brussels-Capital Region' },
    { value: 'WHT', label: 'Hainaut' },
    { value: 'VLI', label: 'Limburg' },
    { value: 'WLG', label: 'Liège' },
    { value: 'WLX', label: 'Luxembourg' },
    { value: 'WNA', label: 'Namur' },
    { value: 'VOV', label: 'East Flanders' },
    { value: 'VBR', label: 'Flemish Brabant' },
    { value: 'VWV', label: 'West Flanders' },
  ],
  BG: [
    { value: '01', label: 'Blagoevgrad' },
    { value: '02', label: 'Burgas' },
    { value: '03', label: 'Varna' },
    { value: '04', label: 'Veliko Tarnovo' },
    { value: '05', label: 'Vidin' },
    { value: '06', label: 'Vratsa' },
    { value: '07', label: 'Gabrovo' },
    { value: '08', label: 'Dobrich' },
    { value: '09', label: 'Kardzhali' },
    { value: '10', label: 'Kyustendil' },
    { value: '11', label: 'Lovech' },
    { value: '12', label: 'Montana' },
    { value: '13', label: 'Pazardzhik' },
    { value: '14', label: 'Pernik' },
    { value: '15', label: 'Pleven' },
    { value: '16', label: 'Plovdiv' },
    { value: '17', label: 'Razgrad' },
    { value: '18', label: 'Ruse' },
    { value: '19', label: 'Silistra' },
    { value: '20', label: 'Sliven' },
    { value: '21', label: 'Smolyan' },
    { value: '22', label: 'Sofia' },
    { value: '23', label: 'Sofia City' },
    { value: '24', label: 'Stara Zagora' },
    { value: '25', label: 'Targovishte' },
    { value: '26', label: 'Haskovo' },
    { value: '27', label: 'Shumen' },
    { value: '28', label: 'Yambol' },
  ],
  CH: [
    { value: 'AG', label: 'Aargau' },
    { value: 'AI', label: 'Appenzell Innerrhoden' },
    { value: 'AR', label: 'Appenzell Ausserrhoden' },
    { value: 'BE', label: 'Bern' },
    { value: 'BL', label: 'Basel-Landschaft' },
    { value: 'BS', label: 'Basel-Stadt' },
    { value: 'FR', label: 'Fribourg' },
    { value: 'GE', label: 'Geneva' },
    { value: 'GL', label: 'Glarus' },
    { value: 'GR', label: 'Graubünden' },
    { value: 'JU', label: 'Jura' },
    { value: 'LU', label: 'Lucerne' },
    { value: 'NE', label: 'Neuchâtel' },
    { value: 'NW', label: 'Nidwalden' },
    { value: 'OW', label: 'Obwalden' },
    { value: 'SG', label: 'St. Gallen' },
    { value: 'SH', label: 'Schaffhausen' },
    { value: 'SO', label: 'Solothurn' },
    { value: 'SZ', label: 'Schwyz' },
    { value: 'TG', label: 'Thurgau' },
    { value: 'TI', label: 'Ticino' },
    { value: 'UR', label: 'Uri' },
    { value: 'VD', label: 'Vaud' },
    { value: 'VS', label: 'Valais' },
    { value: 'ZG', label: 'Zug' },
    { value: 'ZH', label: 'Zürich' },
  ],
  CY: [
    { value: '01', label: 'Lefkosia' },
    { value: '02', label: 'Lemesos' },
    { value: '03', label: 'Larnaka' },
    { value: '04', label: 'Ammochostos' },
    { value: '05', label: 'Pafos' },
    { value: '06', label: 'Keryneia' },
  ],
  CZ: [
    { value: '10', label: 'Prague' },
    { value: '20', label: 'Central Bohemian Region' },
    { value: '31', label: 'South Bohemian Region' },
    { value: '32', label: 'Plzen Region' },
    { value: '41', label: 'Karlovy Vary Region' },
    { value: '42', label: 'Ústí nad Labem Region' },
    { value: '51', label: 'Liberec Region' },
    { value: '52', label: 'Hradec Králové Region' },
    { value: '53', label: 'Pardubice Region' },
    { value: '63', label: 'Vysočina Region' },
    { value: '64', label: 'South Moravian Region' },
    { value: '71', label: 'Olomouc Region' },
    { value: '72', label: 'Zlín Region' },
    { value: '80', label: 'Moravian-Silesian Region' },
  ],
  DE: [
    { value: 'BW', label: 'Baden-Württemberg' },
    { value: 'BY', label: 'Bavaria' },
    { value: 'BE', label: 'Berlin' },
    { value: 'BB', label: 'Brandenburg' },
    { value: 'HB', label: 'Bremen' },
    { value: 'HH', label: 'Hamburg' },
    { value: 'HE', label: 'Hesse' },
    { value: 'MV', label: 'Mecklenburg-Vorpommern' },
    { value: 'NI', label: 'Lower Saxony' },
    { value: 'NW', label: 'North Rhine-Westphalia' },
    { value: 'RP', label: 'Rhineland-Palatinate' },
    { value: 'SL', label: 'Saarland' },
    { value: 'SN', label: 'Saxony' },
    { value: 'ST', label: 'Saxony-Anhalt' },
    { value: 'SH', label: 'Schleswig-Holstein' },
    { value: 'TH', label: 'Thuringia' },
  ],
  DK: [
    { value: '84', label: 'Capital Region of Denmark' },
    { value: '82', label: 'Central Denmark Region' },
    { value: '81', label: 'North Denmark Region' },
    { value: '85', label: 'Region Zealand' },
    { value: '83', label: 'Region of Southern Denmark' },
  ],
  EE: [
    { value: '37', label: 'Harju County' },
    { value: '39', label: 'Hiiu County' },
    { value: '44', label: 'Ida-Viru County' },
    { value: '49', label: 'Jõgeva County' },
    { value: '51', label: 'Järva County' },
    { value: '57', label: 'Lääne County' },
    { value: '59', label: 'Lääne-Viru County' },
    { value: '65', label: 'Põlva County' },
    { value: '67', label: 'Pärnu County' },
    { value: '70', label: 'Rapla County' },
    { value: '74', label: 'Saare County' },
    { value: '78', label: 'Tartu County' },
    { value: '82', label: 'Valga County' },
    { value: '84', label: 'Viljandi County' },
    { value: '86', label: 'Võru County' },
  ],
  ES: [
    { value: 'AN', label: 'Andalusia' },
    { value: 'AR', label: 'Aragon' },
    { value: 'AS', label: 'Asturias' },
    { value: 'IB', label: 'Balearic Islands' },
    { value: 'PV', label: 'Basque Country' },
    { value: 'CN', label: 'Canary Islands' },
    { value: 'CB', label: 'Cantabria' },
    { value: 'CM', label: 'Castile-La Mancha' },
    { value: 'CL', label: 'Castile and León' },
    { value: 'CT', label: 'Catalonia' },
    { value: 'EX', label: 'Extremadura' },
    { value: 'GA', label: 'Galicia' },
    { value: 'MD', label: 'Community of Madrid' },
    { value: 'MC', label: 'Region of Murcia' },
    { value: 'NC', label: 'Navarre' },
    { value: 'RI', label: 'La Rioja' },
    { value: 'VC', label: 'Valencian Community' },
    { value: 'CE', label: 'Ceuta' },
    { value: 'ML', label: 'Melilla' },
  ],
  FI: [
    { value: '01', label: 'Åland' },
    { value: '02', label: 'South Karelia' },
    { value: '03', label: 'Southern Ostrobothnia' },
    { value: '04', label: 'Southern Savonia' },
    { value: '05', label: 'Kainuu' },
    { value: '06', label: 'Tavastia Proper' },
    { value: '07', label: 'Central Ostrobothnia' },
    { value: '08', label: 'Central Finland' },
    { value: '09', label: 'Kymenlaakso' },
    { value: '10', label: 'Lapland' },
    { value: '11', label: 'Pirkanmaa' },
    { value: '12', label: 'Ostrobothnia' },
    { value: '13', label: 'North Karelia' },
    { value: '14', label: 'Northern Ostrobothnia' },
    { value: '15', label: 'Northern Savonia' },
    { value: '16', label: 'Päijänne Tavastia' },
    { value: '17', label: 'Satakunta' },
    { value: '18', label: 'Uusimaa' },
    { value: '19', label: 'Southwest Finland' },
  ],
  FR: [
    { value: 'ARA', label: 'Auvergne-Rhône-Alpes' },
    { value: 'BFC', label: 'Bourgogne-Franche-Comté' },
    { value: 'BRE', label: 'Brittany' },
    { value: 'CVL', label: 'Centre-Val de Loire' },
    { value: '20R', label: 'Corsica' },
    { value: 'GES', label: 'Grand Est' },
    { value: 'HDF', label: 'Hauts-de-France' },
    { value: 'IDF', label: 'Île-de-France' },
    { value: 'NOR', label: 'Normandy' },
    { value: 'NAQ', label: 'Nouvelle-Aquitaine' },
    { value: 'OCC', label: 'Occitania' },
    { value: 'PDL', label: 'Pays de la Loire' },
    { value: 'PAC', label: 'Provence-Alpes-Côte d\'Azur' },
  ],
  GB: [
    { value: 'ENG', label: 'England' },
    { value: 'SCT', label: 'Scotland' },
    { value: 'WLS', label: 'Wales' },
    { value: 'NIR', label: 'Northern Ireland' },
  ],
  GR: [
    { value: 'A', label: 'Attica' },
    { value: 'I', label: 'North Aegean' },
    { value: 'J', label: 'South Aegean' },
    { value: 'K', label: 'Crete' },
    { value: 'L', label: 'Eastern Macedonia and Thrace' },
    { value: 'M', label: 'Central Macedonia' },
    { value: 'N', label: 'Western Macedonia' },
    { value: 'H', label: 'Thessaly' },
    { value: 'F', label: 'Ionian Islands' },
    { value: 'G', label: 'Western Greece' },
    { value: 'D', label: 'Central Greece' },
    { value: 'C', label: 'Peloponnese' },
    { value: 'B', label: 'Epirus' },
  ],
  HR: [
    { value: '21', label: 'City of Zagreb' },
    { value: '07', label: 'Zagreb County' },
    { value: '12', label: 'Krapina-Zagorje County' },
    { value: '19', label: 'Sisak-Moslavina County' },
    { value: '04', label: 'Karlovac County' },
    { value: '06', label: 'Varaždin County' },
    { value: '02', label: 'Koprivnica-Križevci County' },
    { value: '05', label: 'Bjelovar-Bilogora County' },
    { value: '03', label: 'Primorje-Gorski Kotar County' },
    { value: '09', label: 'Lika-Senj County' },
    { value: '16', label: 'Virovitica-Podravina County' },
    { value: '14', label: 'Požega-Slavonia County' },
    { value: '11', label: 'Brod-Posavina County' },
    { value: '20', label: 'Zadar County' },
    { value: '15', label: 'Osijek-Baranja County' },
    { value: '13', label: 'Šibenik-Knin County' },
    { value: '17', label: 'Vukovar-Syrmia County' },
    { value: '10', label: 'Split-Dalmatia County' },
    { value: '01', label: 'Istria County' },
    { value: '08', label: 'Dubrovnik-Neretva County' },
  ],
  HU: [
    { value: 'BU', label: 'Budapest' },
    { value: 'BK', label: 'Bács-Kiskun' },
    { value: 'BA', label: 'Baranya' },
    { value: 'BE', label: 'Békés' },
    { value: 'BZ', label: 'Borsod-Abaúj-Zemplén' },
    { value: 'CS', label: 'Csongrád-Csanád' },
    { value: 'FE', label: 'Fejér' },
    { value: 'GS', label: 'Győr-Moson-Sopron' },
    { value: 'HB', label: 'Hajdú-Bihar' },
    { value: 'HE', label: 'Heves' },
    { value: 'JN', label: 'Jász-Nagykun-Szolnok' },
    { value: 'KE', label: 'Komárom-Esztergom' },
    { value: 'NO', label: 'Nógrád' },
    { value: 'PE', label: 'Pest' },
    { value: 'SO', label: 'Somogy' },
    { value: 'SZ', label: 'Szabolcs-Szatmár-Bereg' },
    { value: 'TO', label: 'Tolna' },
    { value: 'VA', label: 'Vas' },
    { value: 'VE', label: 'Veszprém' },
    { value: 'ZA', label: 'Zala' },
  ],
  IE: [
    { value: 'C', label: 'Connacht' },
    { value: 'L', label: 'Leinster' },
    { value: 'M', label: 'Munster' },
    { value: 'U', label: 'Ulster' },
  ],
  IS: [
    { value: '1', label: 'Capital Region' },
    { value: '2', label: 'Southern Peninsula' },
    { value: '3', label: 'Western Region' },
    { value: '4', label: 'Westfjords' },
    { value: '5', label: 'Northwestern Region' },
    { value: '6', label: 'Northeastern Region' },
    { value: '7', label: 'Eastern Region' },
    { value: '8', label: 'Southern Region' },
  ],
  IT: [
    { value: '65', label: 'Abruzzo' },
    { value: '77', label: 'Basilicata' },
    { value: '78', label: 'Calabria' },
    { value: '72', label: 'Campania' },
    { value: '45', label: 'Emilia-Romagna' },
    { value: '36', label: 'Friuli-Venezia Giulia' },
    { value: '62', label: 'Lazio' },
    { value: '42', label: 'Liguria' },
    { value: '25', label: 'Lombardy' },
    { value: '57', label: 'Marche' },
    { value: '67', label: 'Molise' },
    { value: '21', label: 'Piedmont' },
    { value: '75', label: 'Apulia' },
    { value: '88', label: 'Sardinia' },
    { value: '82', label: 'Sicily' },
    { value: '52', label: 'Tuscany' },
    { value: '32', label: 'Trentino-Alto Adige' },
    { value: '55', label: 'Umbria' },
    { value: '23', label: 'Aosta Valley' },
    { value: '34', label: 'Veneto' },
  ],
  LT: [
    { value: 'AL', label: 'Alytus County' },
    { value: 'KU', label: 'Kaunas County' },
    { value: 'KL', label: 'Klaipėda County' },
    { value: 'MR', label: 'Marijampolė County' },
    { value: 'PN', label: 'Panevėžys County' },
    { value: 'SA', label: 'Šiauliai County' },
    { value: 'TA', label: 'Tauragė County' },
    { value: 'TE', label: 'Telšiai County' },
    { value: 'UT', label: 'Utena County' },
    { value: 'VL', label: 'Vilnius County' },
  ],
  LU: [
    { value: 'D', label: 'Diekirch' },
    { value: 'G', label: 'Grevenmacher' },
    { value: 'L', label: 'Luxembourg' },
  ],
  LV: [
    { value: '002', label: 'Aizkraukle Municipality' },
    { value: '007', label: 'Alūksne Municipality' },
    { value: '011', label: 'Ādaži Municipality' },
    { value: '015', label: 'Balvi Municipality' },
    { value: '016', label: 'Bauska Municipality' },
    { value: '022', label: 'Cēsis Municipality' },
    { value: '026', label: 'Dobele Municipality' },
    { value: '033', label: 'Gulbene Municipality' },
    { value: '041', label: 'Jelgava Municipality' },
    { value: '042', label: 'Jelgava' },
    { value: '047', label: 'Krāslava Municipality' },
    { value: '050', label: 'Kuldīga Municipality' },
    { value: '052', label: 'Liepāja Municipality' },
    { value: '053', label: 'Liepāja' },
    { value: '058', label: 'Limbaži Municipality' },
    { value: '059', label: 'Ludza Municipality' },
    { value: '062', label: 'Madona Municipality' },
    { value: '067', label: 'Ogre Municipality' },
    { value: '068', label: 'Olaine Municipality' },
    { value: '073', label: 'Preiļi Municipality' },
    { value: '077', label: 'Rēzekne Municipality' },
    { value: '078', label: 'Rēzekne' },
    { value: '079', label: 'Riga Municipality' },
    { value: 'RIX', label: 'Riga' },
    { value: '080', label: 'Saldus Municipality' },
    { value: '087', label: 'Talsi Municipality' },
    { value: '089', label: 'Tukums Municipality' },
    { value: '091', label: 'Valka Municipality' },
    { value: '094', label: 'Valmiera' },
    { value: '101', label: 'Ventspils Municipality' },
    { value: '102', label: 'Ventspils' },
  ],
  MT: [
    { value: '01', label: 'Southern Harbour' },
    { value: '02', label: 'Northern Harbour' },
    { value: '03', label: 'South Eastern' },
    { value: '04', label: 'Western' },
    { value: '05', label: 'Northern' },
    { value: '06', label: 'Gozo and Comino' },
  ],
  NL: [
    { value: 'DR', label: 'Drenthe' },
    { value: 'FL', label: 'Flevoland' },
    { value: 'FR', label: 'Friesland' },
    { value: 'GE', label: 'Gelderland' },
    { value: 'GR', label: 'Groningen' },
    { value: 'LI', label: 'Limburg' },
    { value: 'NB', label: 'North Brabant' },
    { value: 'NH', label: 'North Holland' },
    { value: 'OV', label: 'Overijssel' },
    { value: 'UT', label: 'Utrecht' },
    { value: 'ZE', label: 'Zeeland' },
    { value: 'ZH', label: 'South Holland' },
  ],
  NO: [
    { value: '15', label: 'Møre og Romsdal' },
    { value: '18', label: 'Nordland' },
    { value: '30', label: 'Viken' },
    { value: '34', label: 'Innlandet' },
    { value: '38', label: 'Vestfold og Telemark' },
    { value: '42', label: 'Agder' },
    { value: '46', label: 'Vestland' },
    { value: '50', label: 'Trøndelag' },
    { value: '54', label: 'Troms og Finnmark' },
    { value: '03', label: 'Oslo' },
    { value: '11', label: 'Rogaland' },
  ],
  PL: [
    { value: '02', label: 'Lower Silesian Voivodeship' },
    { value: '04', label: 'Kuyavian-Pomeranian Voivodeship' },
    { value: '06', label: 'Lublin Voivodeship' },
    { value: '08', label: 'Lubusz Voivodeship' },
    { value: '10', label: 'Łódź Voivodeship' },
    { value: '12', label: 'Lesser Poland Voivodeship' },
    { value: '14', label: 'Masovian Voivodeship' },
    { value: '16', label: 'Opole Voivodeship' },
    { value: '18', label: 'Subcarpathian Voivodeship' },
    { value: '20', label: 'Podlaskie Voivodeship' },
    { value: '22', label: 'Pomeranian Voivodeship' },
    { value: '24', label: 'Silesian Voivodeship' },
    { value: '26', label: 'Świętokrzyskie Voivodeship' },
    { value: '28', label: 'Warmian-Masurian Voivodeship' },
    { value: '30', label: 'Greater Poland Voivodeship' },
    { value: '32', label: 'West Pomeranian Voivodeship' },
  ],
  PT: [
    { value: '01', label: 'Aveiro' },
    { value: '02', label: 'Beja' },
    { value: '03', label: 'Braga' },
    { value: '04', label: 'Bragança' },
    { value: '05', label: 'Castelo Branco' },
    { value: '06', label: 'Coimbra' },
    { value: '07', label: 'Évora' },
    { value: '08', label: 'Faro' },
    { value: '09', label: 'Guarda' },
    { value: '10', label: 'Leiria' },
    { value: '11', label: 'Lisboa' },
    { value: '12', label: 'Portalegre' },
    { value: '13', label: 'Porto' },
    { value: '14', label: 'Santarém' },
    { value: '15', label: 'Setúbal' },
    { value: '16', label: 'Viana do Castelo' },
    { value: '17', label: 'Vila Real' },
    { value: '18', label: 'Viseu' },
    { value: '20', label: 'Azores' },
    { value: '30', label: 'Madeira' },
  ],
  RO: [
    { value: 'AB', label: 'Alba' },
    { value: 'AR', label: 'Arad' },
    { value: 'AG', label: 'Argeș' },
    { value: 'BC', label: 'Bacău' },
    { value: 'BH', label: 'Bihor' },
    { value: 'BN', label: 'Bistrița-Năsăud' },
    { value: 'BT', label: 'Botoșani' },
    { value: 'BV', label: 'Brașov' },
    { value: 'BR', label: 'Brăila' },
    { value: 'B', label: 'Bucharest' },
    { value: 'BZ', label: 'Buzău' },
    { value: 'CS', label: 'Caraș-Severin' },
    { value: 'CL', label: 'Călărași' },
    { value: 'CJ', label: 'Cluj' },
    { value: 'CT', label: 'Constanța' },
    { value: 'CV', label: 'Covasna' },
    { value: 'DB', label: 'Dâmbovița' },
    { value: 'DJ', label: 'Dolj' },
    { value: 'GL', label: 'Galați' },
    { value: 'GR', label: 'Giurgiu' },
    { value: 'GJ', label: 'Gorj' },
    { value: 'HR', label: 'Harghita' },
    { value: 'HD', label: 'Hunedoara' },
    { value: 'IL', label: 'Ialomița' },
    { value: 'IS', label: 'Iași' },
    { value: 'IF', label: 'Ilfov' },
    { value: 'MM', label: 'Maramureș' },
    { value: 'MH', label: 'Mehedinți' },
    { value: 'MS', label: 'Mureș' },
    { value: 'NT', label: 'Neamț' },
    { value: 'OT', label: 'Olt' },
    { value: 'PH', label: 'Prahova' },
    { value: 'SM', label: 'Satu Mare' },
    { value: 'SJ', label: 'Sălaj' },
    { value: 'SB', label: 'Sibiu' },
    { value: 'SV', label: 'Suceava' },
    { value: 'TR', label: 'Teleorman' },
    { value: 'TM', label: 'Timiș' },
    { value: 'TL', label: 'Tulcea' },
    { value: 'VS', label: 'Vaslui' },
    { value: 'VL', label: 'Vâlcea' },
    { value: 'VN', label: 'Vrancea' },
  ],
  SE: [
    { value: 'K', label: 'Blekinge County' },
    { value: 'W', label: 'Dalarna County' },
    { value: 'I', label: 'Gotland County' },
    { value: 'X', label: 'Gävleborg County' },
    { value: 'N', label: 'Halland County' },
    { value: 'Z', label: 'Jämtland County' },
    { value: 'F', label: 'Jönköping County' },
    { value: 'H', label: 'Kalmar County' },
    { value: 'G', label: 'Kronoberg County' },
    { value: 'BD', label: 'Norrbotten County' },
    { value: 'M', label: 'Skåne County' },
    { value: 'AB', label: 'Stockholm County' },
    { value: 'D', label: 'Södermanland County' },
    { value: 'C', label: 'Uppsala County' },
    { value: 'S', label: 'Värmland County' },
    { value: 'AC', label: 'Västerbotten County' },
    { value: 'Y', label: 'Västernorrland County' },
    { value: 'U', label: 'Västmanland County' },
    { value: 'O', label: 'Västra Götaland County' },
    { value: 'T', label: 'Örebro County' },
    { value: 'E', label: 'Östergötland County' },
  ],
  SI: [
    { value: '001', label: 'Ajdovščina' },
    { value: '195', label: 'Apače' },
    { value: '002', label: 'Beltinci' },
    { value: '148', label: 'Benedikt' },
    { value: '149', label: 'Bistrica ob Sotli' },
    { value: '003', label: 'Bled' },
    { value: '150', label: 'Bloke' },
    { value: '004', label: 'Bohinj' },
    { value: '005', label: 'Borovnica' },
    { value: '006', label: 'Bovec' },
    { value: '151', label: 'Braslovče' },
    { value: '007', label: 'Brda' },
    { value: '008', label: 'Brezovica' },
    { value: '009', label: 'Brežice' },
    { value: '152', label: 'Cankova' },
    { value: '011', label: 'Celje' },
    { value: '012', label: 'Cerklje na Gorenjskem' },
    { value: '013', label: 'Cerknica' },
    { value: '014', label: 'Cerkno' },
    { value: '153', label: 'Cerkvenjak' },
    { value: '196', label: 'Cirkulane' },
    { value: '015', label: 'Črenšovci' },
    { value: '016', label: 'Črna na Koroškem' },
    { value: '017', label: 'Črnomelj' },
    { value: '018', label: 'Destrnik' },
    { value: '019', label: 'Divača' },
    { value: '154', label: 'Dobje' },
    { value: '020', label: 'Dobrepolje' },
    { value: '155', label: 'Dobrna' },
    { value: '021', label: 'Dobrova–Polhov Gradec' },
    { value: '156', label: 'Dobrovnik' },
    { value: '022', label: 'Dol pri Ljubljani' },
    { value: '157', label: 'Dolenjske Toplice' },
    { value: '023', label: 'Domžale' },
    { value: '024', label: 'Dornava' },
    { value: '025', label: 'Dravograd' },
    { value: '026', label: 'Duplek' },
    { value: '027', label: 'Gorenja Vas–Poljane' },
    { value: '028', label: 'Gorišnica' },
    { value: '207', label: 'Gorje' },
    { value: '029', label: 'Gornja Radgona' },
    { value: '030', label: 'Gornji Grad' },
    { value: '031', label: 'Gornji Petrovci' },
    { value: '158', label: 'Grad' },
    { value: '032', label: 'Grosuplje' },
    { value: '159', label: 'Hajdina' },
    { value: '160', label: 'Hoče–Slivnica' },
    { value: '161', label: 'Hodoš' },
    { value: '162', label: 'Horjul' },
    { value: '034', label: 'Hrastnik' },
    { value: '035', label: 'Hrpelje–Kozina' },
    { value: '036', label: 'Idrija' },
    { value: '037', label: 'Ig' },
    { value: '038', label: 'Ilirska Bistrica' },
    { value: '039', label: 'Ivančna Gorica' },
    { value: '040', label: 'Izola' },
    { value: '041', label: 'Jesenice' },
    { value: '163', label: 'Jezersko' },
    { value: '042', label: 'Juršinci' },
    { value: '043', label: 'Kamnik' },
    { value: '044', label: 'Kanal' },
    { value: '045', label: 'Kidričevo' },
    { value: '046', label: 'Kobarid' },
    { value: '047', label: 'Kobilje' },
    { value: '048', label: 'Kočevje' },
    { value: '049', label: 'Komen' },
    { value: '164', label: 'Komenda' },
    { value: '050', label: 'Koper' },
    { value: '197', label: 'Kostanjevica na Krki' },
    { value: '165', label: 'Kostel' },
    { value: '051', label: 'Kozje' },
    { value: '052', label: 'Kranj' },
    { value: '053', label: 'Kranjska Gora' },
    { value: '166', label: 'Križevci' },
    { value: '054', label: 'Krško' },
    { value: '055', label: 'Kungota' },
    { value: '056', label: 'Kuzma' },
    { value: '057', label: 'Laško' },
    { value: '058', label: 'Lenart' },
    { value: '059', label: 'Lendava' },
    { value: '060', label: 'Litija' },
    { value: '061', label: 'Ljubljana' },
    { value: '062', label: 'Ljubno' },
    { value: '063', label: 'Ljutomer' },
    { value: '208', label: 'Log–Dragomer' },
    { value: '064', label: 'Logatec' },
    { value: '167', label: 'Loška Dolina' },
    { value: '065', label: 'Loški Potok' },
    { value: '066', label: 'Lovrenc na Pohorju' },
    { value: '067', label: 'Luče' },
    { value: '068', label: 'Lukovica' },
    { value: '069', label: 'Majšperk' },
    { value: '198', label: 'Makole' },
    { value: '070', label: 'Maribor' },
    { value: '168', label: 'Markovci' },
    { value: '071', label: 'Medvode' },
    { value: '072', label: 'Mengeš' },
    { value: '073', label: 'Metlika' },
    { value: '074', label: 'Mežica' },
    { value: '169', label: 'Miklavž na Dravskem Polju' },
    { value: '075', label: 'Miren–Kostanjevica' },
    { value: '212', label: 'Mirna' },
    { value: '170', label: 'Mirna Peč' },
    { value: '076', label: 'Mislinja' },
    { value: '199', label: 'Mokronog–Trebelno' },
    { value: '077', label: 'Moravče' },
    { value: '078', label: 'Moravske Toplice' },
    { value: '079', label: 'Mozirje' },
    { value: '080', label: 'Murska Sobota' },
    { value: '081', label: 'Muta' },
    { value: '082', label: 'Naklo' },
    { value: '083', label: 'Nazarje' },
    { value: '084', label: 'Nova Gorica' },
    { value: '085', label: 'Novo Mesto' },
    { value: '086', label: 'Odranci' },
    { value: '171', label: 'Oplotnica' },
    { value: '087', label: 'Ormož' },
    { value: '088', label: 'Osilnica' },
    { value: '089', label: 'Pesnica' },
    { value: '090', label: 'Piran' },
    { value: '091', label: 'Pivka' },
    { value: '092', label: 'Podčetrtek' },
    { value: '172', label: 'Podlehnik' },
    { value: '093', label: 'Podvelka' },
    { value: '200', label: 'Poljčane' },
    { value: '173', label: 'Polzela' },
    { value: '094', label: 'Postojna' },
    { value: '174', label: 'Prebold' },
    { value: '095', label: 'Preddvor' },
    { value: '175', label: 'Prevalje' },
    { value: '096', label: 'Ptuj' },
    { value: '097', label: 'Puconci' },
    { value: '098', label: 'Rače–Fram' },
    { value: '099', label: 'Radeče' },
    { value: '100', label: 'Radenci' },
    { value: '101', label: 'Radlje ob Dravi' },
    { value: '102', label: 'Radovljica' },
    { value: '103', label: 'Ravne na Koroškem' },
    { value: '176', label: 'Razkrižje' },
    { value: '209', label: 'Rečica ob Savinji' },
    { value: '201', label: 'Renče–Vogrsko' },
    { value: '104', label: 'Ribnica' },
    { value: '177', label: 'Ribnica na Pohorju' },
    { value: '106', label: 'Rogaška Slatina' },
    { value: '105', label: 'Rogašovci' },
    { value: '107', label: 'Rogatec' },
    { value: '108', label: 'Ruše' },
    { value: '178', label: 'Selnica ob Dravi' },
    { value: '109', label: 'Semič' },
    { value: '110', label: 'Sevnica' },
    { value: '111', label: 'Sežana' },
    { value: '112', label: 'Slovenj Gradec' },
    { value: '113', label: 'Slovenska Bistrica' },
    { value: '114', label: 'Slovenske Konjice' },
    { value: '179', label: 'Sodražica' },
    { value: '180', label: 'Solčava' },
    { value: '202', label: 'Središče ob Dravi' },
    { value: '115', label: 'Starše' },
    { value: '203', label: 'Straža' },
    { value: '181', label: 'Sveta Ana' },
    { value: '204', label: 'Sveta Trojica v Slovenskih Goricah' },
    { value: '182', label: 'Sveti Andraž v Slovenskih Goricah' },
    { value: '116', label: 'Sveti Jurij' },
    { value: '210', label: 'Sveti Jurij v Slovenskih Goricah' },
    { value: '205', label: 'Sveti Tomaž' },
    { value: '033', label: 'Šalovci' },
    { value: '183', label: 'Šempeter–Vrtojba' },
    { value: '117', label: 'Šenčur' },
    { value: '118', label: 'Šentilj' },
    { value: '119', label: 'Šentjernej' },
    { value: '120', label: 'Šentjur' },
    { value: '211', label: 'Šentrupert' },
    { value: '121', label: 'Škocjan' },
    { value: '122', label: 'Škofja Loka' },
    { value: '123', label: 'Škofljica' },
    { value: '124', label: 'Šmarje pri Jelšah' },
    { value: '206', label: 'Šmarješke Toplice' },
    { value: '125', label: 'Šmartno ob Paki' },
    { value: '194', label: 'Šmartno pri Litiji' },
    { value: '126', label: 'Šoštanj' },
    { value: '127', label: 'Štore' },
    { value: '184', label: 'Tabor' },
    { value: '010', label: 'Tišina' },
    { value: '128', label: 'Tolmin' },
    { value: '129', label: 'Trbovlje' },
    { value: '130', label: 'Trebnje' },
    { value: '185', label: 'Trnovska Vas' },
    { value: '131', label: 'Tržič' },
    { value: '186', label: 'Trzin' },
    { value: '132', label: 'Turnišče' },
    { value: '133', label: 'Velenje' },
    { value: '187', label: 'Velika Polana' },
    { value: '134', label: 'Velike Lašče' },
    { value: '188', label: 'Veržej' },
    { value: '135', label: 'Videm' },
    { value: '136', label: 'Vipava' },
    { value: '137', label: 'Vitanje' },
    { value: '138', label: 'Vodice' },
    { value: '139', label: 'Vojnik' },
    { value: '189', label: 'Vransko' },
    { value: '140', label: 'Vrhnika' },
    { value: '141', label: 'Vuzenica' },
    { value: '142', label: 'Zagorje ob Savi' },
    { value: '143', label: 'Zavrč' },
    { value: '144', label: 'Zreče' },
    { value: '190', label: 'Žalec' },
    { value: '146', label: 'Železniki' },
    { value: '191', label: 'Žetale' },
    { value: '147', label: 'Žiri' },
    { value: '192', label: 'Žirovnica' },
    { value: '193', label: 'Žužemberk' },
  ],
  SK: [
    { value: 'BC', label: 'Banská Bystrica Region' },
    { value: 'BL', label: 'Bratislava Region' },
    { value: 'KI', label: 'Košice Region' },
    { value: 'NI', label: 'Nitra Region' },
    { value: 'PV', label: 'Prešov Region' },
    { value: 'TC', label: 'Trenčín Region' },
    { value: 'TA', label: 'Trnava Region' },
    { value: 'ZI', label: 'Žilina Region' },
  ],
}

/**
 * Get European subdivisions for a specific country
 */
export function getEuropeanSubdivisions(countryCode: string): StateOption[] {
  return EUROPEAN_SUBDIVISIONS[countryCode] || []
}

/**
 * Check if a country has European subdivisions
 */
export function hasEuropeanSubdivisions(countryCode: string): boolean {
  return countryCode in EUROPEAN_SUBDIVISIONS
}

/**
 * Get all European country codes that have subdivisions
 */
export function getEuropeanCountryCodes(): string[] {
  return Object.keys(EUROPEAN_SUBDIVISIONS)
}
